[mypy]
python_version = 3.14
files = quickly
mypy_path = ../parce
warn_redundant_casts = True
warn_unused_ignores = True
enable_error_code = ignore-without-code, possibly-undefined

[mypy-parce.*]
follow_imports = silent

[mypy-quickly,quickly.pkginfo,quickly.datatypes,quickly.numbering,quickly.duration,quickly.dom,quickly.lang]
disallow_untyped_defs = True
disallow_incomplete_defs = True